version: "3.7"
services:
  x:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run
  mysqlserver:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=dadalang
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=x
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: